### ISSUE TITLE
Basic client to talk to the oracle

### ISSUE THREAD

**Issue by RangerMauve** [KenCloud-Tech/prolly-tree-oracle#5]
We should put together a basic client to talk to the oracle.

It should:
- Have a way to connect to a wallet (metamask?)
- Specify the smart contract id for the oracle
- Support all the functions from the contract
- Either be a basic web app (I can help put the ui together) or a CLI command

I'm not sure what the best options for this are so feedback is welcome. We just need people to be able to test the functions, not a full app.

**Comment by EdisionJ** [comment]
1. I don’t quite understand what `Specify the smart contract id for the oracle` means. Does it mean we will deploy multiple oracles and should specify an ID for each oracle?  
2.  Considering our oracle task, I think the client is better to use CLI, and the web app is not necessary.

**Comment by RangerMauve** [comment]
1. Yes there could be multiple oracles deployed so the client should be able to specify which one it talks to. We might also need to pass in the specific network we're talking to. Does etherium have a testnet we could deploy to?

2. My only concern with cli approaches is how we expect the client to access their wallet. I've only really seen native apps and browser extensions for wallets so we might need to pick at least one of those for the cli.
